name: Skaffold Build Action
description: Setup Skaffold and all required dependencies
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  default-repo:
    default: ''
    description: Choose which artifacts to build. Artifacts with image names that contain the expression will be built only. Default is to build sources for all artifacts
    required: false
  tag:
    default: 'latest'
    required: false
    description: The optional custom tag to use for images which overrides the current Tagger configuration
  build-image:
    default: ''
    description: Skaffold version
    required: false
  profile:
    default: ''
    description: Activate profiles by name (prefixed with `-` to disable a profile)
    required: false
  skip-tests:
    default: 'false'
    description: Whether to skip the tests after building
    required: false
  args:
    default: 'build'
    description: Whether to skip the tests after building
    required: false
  entrypoint:
    default: 'skaffold'
    required: false
    description: Entrypoint
  workdir:
    default: '.'
    required: false
    description: Workdir
outputs: {}
runs:
  using: docker
  image: docker://miklosn/skaffold:latest
  env:
    SKAFFOLD_DEFAULT_REPO: ${{ inputs.default-repo }}
    SKAFFOLD_PROFILE: ${{ inputs.profile }}
    SKAFFOLD_TAG: ${{ inputs.tag }}
    SKAFFOLD_BUILD_IMAGE: ${{ inputs.build-image }}
    SKAFFOLD_SKIP_TESTS : ${{ inputs.skip-tests }}
    WORKDIR : ${{ inputs.workdir }}
